[project]
name = "diplomska-naloga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "panjanjan", email = "jan.panjan01@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.4.0",
    "mdanalysis>=2.10.0",
]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
