```{r libs, message=FALSE}
library(dplyr)
library(ggplot2)
httpgd::hgd()
```

# Primer kako matchat domene z RMSF

```{r sword_results}
domains <- read.csv("sword_results_clean.csv") |>
    as_tibble() |>
    group_by(protein)
domains
```

```{r rmsf_file}
prot <- "1dd3_A"
files <- list.files(path = "atlas_db/RMSF", pattern = prot, full.names = TRUE)
rmsf <- read.delim(files) |> as_tibble()
rmsf
```

Ali se velikosti ujemata?

```{r}
example_d <- domains |> filter(protein == prot)
max(example_d$end) == nrow(rmsf)
```

Loči RMSF od obeh domen.

```{r}
# vsebuje 2 domeni, zato imata start/end vektorja 2 elementa
start <- example_d$start
end <- example_d$end

rmsf_1 <- rmsf[start[1]:end[1], ]
rmsf_1

rmsf_2 <- rmsf[start[2]:end[2], ]
rmsf_2

# vse vrstice morajo biti uporabljene
nrow(rmsf_1) + nrow(rmsf_2) == nrow(rmsf)
nrow(rmsf_1) + nrow(rmsf_2) == max(example_d$end)
```

# Primer plottanja replikatov

```{r}
# raztegni data da lahko obarva po replikatu
rmsf_plot <- rmsf |>
    mutate(residue = seq_len(n())) |>
    tidyr::pivot_longer(cols = starts_with("RMSF_R"), names_to = "replicate", values_to = "rmsf")

ggplot(rmsf_plot, aes(x = residue, y = rmsf, color = replicate)) +
    geom_line(size = 0.5, alpha = 0.7) +
    geom_point(size = 1, alpha = 0.7) +
    scale_color_manual(
        values = c(RMSF_R1 = "#ff8e32", RMSF_R2 = "#cd68bb", RMSF_R3 = "#51c3cc"),
        labels = c(RMSF_R1 = "1", RMSF_R2 = "2", RMSF_R3 = "3")
    ) +
    labs(x = "Residue index", y = "RMSF", title = prot) +
    theme_light(base_size = 18) +
    theme(
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#dfe2e5"),
        legend.position = "top",
        legend.title = element_text(face = "bold"),
        plot.title = element_text(face = "bold", hjust = 0.5)
    )
```

#
