---
format:
  html:
    code-fold: true
---


```{r}
#| code-fold: false
library(ggplot2)
library(patchwork)
```

```{r}
#| code-summary: datoteke
source(file.path(Sys.getenv("ROOT"), "scripts", "utils.r"))
data <- load_data("dist")

files <- sapply(head(data), basename)
names(files) <- NULL
files
```

```{r}
#| code-summary: primer
read.csv(data[1]) |> head()
```

```{r}
#| code-summary: psd funkcija
psd <- function(x, protein, replicate) {
    n <- length(x)

    # nastavimo vse razdalje relativno glede na prvo
    # NOTE: mogoče bi to naredil že v shranjenih razdaljah..?
    x <- x - x[1]

    # frekvenca vzorčenja: kolikokrat na časovno enoto vzorčimo (1 ps)
    dt_sec <- 1 * 1e-12
    fs_hz <- 1 / dt_sec # v Hz

    # frekvenčni korak: razmik med točkami v frekvenčni domeni
    #
    # npr. za 100 meritev s frekvenco vzorčenja 1s je najnižja frekvenca, ki jo
    # lahko določimo 0.01 Hz = 1/100 s^-1 <=> 1 cikel na 100 s (samo 1 cikel skozi vse meritve)
    # najvišja frekvenca je enaka velikosti vzorca, n, in je 1 cikel na 1 s <=> 100/100 s^-1 = 1 Hz
    #
    # za primer 1001 meritev s frekvenco vzorčenja 1 ps (1e-12 s = 1/10000...0 s) je
    # najnižja določljiva frekvenca 1/1001 ps^-1 = 0.000999001 * 1e+12 = 0.999001 GHz,
    # najvišja pa 1001/1001 ps^-1 = 1 * 1e+12 Hz = 1 THz (načeloma...)
    df <- fs_hz / n

    # nyquistova frekvenca (N/2) določa do katere (analizne) frekvence se *aliasing*
    # ne dogaja. potrebujemo samo frekvence do te (included), da zajamemo vse.
    half_n <- 1 + floor(n / 2)
    freq <- seq(0, by = df, length.out = half_n)

    # ker merimo 1.001 ns, lahko pretvorimo frekvence iz Hz v ns (nHz...)
    # 999000999 / s = 999000999 / 1e+9 ns = 0.999001 ns^-1 = 0.999001 nHz
    # NOTE: brez DC komponente
    freq_ns <- freq / 1e+9
    freq_ns <- freq_ns[-1]

    # predpostavka DFT je stacionarnost podatkov. odstranjevanje linearnega trenda
    fit <- lm(x ~ seq_along(x))
    x_detrend <- resid(fit)

    # načeloma naj bi imeli manjši proteini nihanja z višjimi frekvencami in večji z
    # manjšimi, zato jih scale-am na [0,1]
    scale_it <- \(v) (v - min(v)) / (max(v) - min(v))

    x_scaled <- scale_it(x_detrend)

    # TODO: spectral leakage?

    # power density estimation
    # NOTE: brez DC komponente
    fft_out <- fft(x_scaled)
    power <- (Mod(fft_out)^2)[2:half_n] |> scale_it()

    # --------------------------------------------------------

    df <- data.frame(time = 1:n, distances = x)
    dfp <- data.frame(frequency = freq_ns, pwr = power)

    plot_scale <- 10

    signal <- df |>
        ggplot(aes(x = time, y = distances)) +
        geom_line() +
        geom_hline(yintercept = median(x), color = "red") +
        labs(
            x = "čas (ps)",
            y = "razdalja (Å)",
            title = paste(protein, replicate),
        ) +
        theme_bw(base_size = plot_scale)
        # theme_bw()

    boxp <- df |>
        ggplot(aes(x = time, y = distances)) +
        geom_boxplot() +
        labs(x = "", y = "") +
        theme_void(base_size = plot_scale)
        # theme_void()

    power_plot <- dfp |>
        ggplot(aes(x = frequency, ymin = 0, ymax = pwr)) +
        geom_linerange() +
        # labs(x = "frekvenca (Hz)", y = "moč", title = "Power Spectral Density (brez DC komponente)") +
        labs(x = "frekvenca (nHz)", y = "moč") +
        theme_bw(base_size = plot_scale)
        # theme_bw()

    print(
        (signal + boxp + plot_layout(widths = c(1, 0.03))) / power_plot
    )
}
```

- Zgornji grafi: razdalja masnih centrov skozi trajektorijo.
- Spodnji grafi: power spectral density brez DC komponente (frekvenca 0).

```{r}
#| warning: false
#| column: screen-inset-shaded
#| layout-ncol: 3
#| code-fold: false

for (dfile in data) {
    d <- read.csv(dfile)
    protein <- sub("_dist.csv", "", basename(dfile))
    psd(d$R1, protein, "R1")
    psd(d$R2, protein, "R2")
    psd(d$R3, protein, "R3")
}
```
